---
swagger: "2.0"
info:
  description: "Provides a RESTful API for interacting with Smartsplit"
  version: "v1"
  title: "Smartsplit API"
  x-origin:
  - format: "yaml"
    url: "https://raw.githubusercontent.com/iptoki/smartsplit/develop/api/swagger.yaml"
  x-providerName: "smartsplit.org"
  x-logo:
    url: "http://smartsplit.org/wp-content/uploads/2019/05/Logo-v02-005-noir.png"
host: "api.smartsplit.org"
basePath: "/v1"
tags:
- name: "Authentication Details"
  description: "Obtaining and refreshing your JWT token"
- name: "Profiles"
  description: "Viewing and creating right holder profiles"
- name: "Media"
  description: "Viewing and creating media"
- name: "Payments"
  description: "Viewing and updating payment details"
schemes:
- "https"
consumes:
- "application/json"
produces:
- "application/json"
security:
- jwt: []
paths:
  /auth:
    post:
      tags:
      - "Authentication Details"
      description: "Get a JWT token for the rest of the requests"
      operationId: "postAuth"
      parameters:
      - in: "body"
        name: "auth"
        description: "JSON string containing your authentication details"
        required: true
        schema:
          $ref: "#/definitions/auth"
      responses:
        200:
          description: "OK. JWT returned for use with the rest of the API requests"
          schema:
            $ref: "#/definitions/authResult"
        401:
          description: "Invalid credentials and/or API token"
      x-swagger-router-controller: "AuthenticationDetails"
  /refreshToken:
    get:
      tags:
      - "Authentication Details"
      description: "Refreshes your current, valid JWT token"
      operationId: "getRefreshToken"
      parameters: []
      responses:
        200:
          description: "OK. JWT returned to use in your subsequent requests"
          schema:
            $ref: "#/definitions/authResult"
        401:
          description: "JWT token is missing or expired"
      security:
      - jwt: []
      x-swagger-router-controller: "AuthenticationDetails"
  /profiles:
    get:
      tags:
      - "Profiles"
      description: "Get a list of all right holder profiles"
      operationId: "getAllProfiles"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/profiles"
        400:
          description: "Bad request"
        403:
          description: "Permission denied"
        404:
          description: "Endpoint not found"
        500:
          description: "An unknown error occured"
      x-swagger-router-controller: "Profiles"
    post:
      tags:
      - "Profiles"
      description: "This method creates a new profile"
      operationId: "postProfile"
      parameters:
      - in: "body"
        name: "body"
        description: "request"
        required: true
        schema:
          $ref: "#/definitions/profile"
      responses:
        200:
          description: "OK. The profile was created."
          schema:
            $ref: "#/definitions/profile"
        400:
          description: "Bad request"
        403:
          description: "Permission denied"
        404:
          description: "Endpoint not found"
        500:
          description: "An unknown error occured"
      security:
      - jwt: []
      x-swagger-router-controller: "Profiles"
  /profiles/{id}:
    get:
      tags:
      - "Profiles"
      description: "Get a right holder's profile with the given ID"
      operationId: "getProfile"
      parameters:
      - name: "id"
        in: "path"
        description: "The rights holder's unique profile ID"
        required: true
        type: "integer"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/profile"
        400:
          description: "Bad request"
        403:
          description: "Permission denied"
        404:
          description: "Endpoint not found"
        500:
          description: "An unknown error occured"
      x-swagger-router-controller: "Profiles"
    put:
      tags:
      - "Profiles"
      description: "This method updates a profile"
      operationId: "updateProfile"
      parameters:
      - name: "id"
        in: "path"
        description: "The rights holder's unique profile ID"
        required: true
        type: "integer"
      - in: "body"
        name: "body"
        description: "request"
        required: true
        schema:
          $ref: "#/definitions/profile"
      responses:
        200:
          description: "OK. The profile was created."
          schema:
            $ref: "#/definitions/profile"
        400:
          description: "Bad request"
        403:
          description: "Permission denied"
        404:
          description: "Endpoint not found"
        500:
          description: "An unknown error occured"
      security:
      - jwt: []
      x-swagger-router-controller: "Profiles"
    delete:
      tags:
      - "Profiles"
      description: "Delete a right holder's profile with the given ID"
      operationId: "deleteProfile"
      parameters:
      - name: "id"
        in: "path"
        description: "The rights holder's unique profile ID"
        required: true
        type: "integer"
      responses:
        200:
          description: "OK. Profile deleted."
        400:
          description: "Bad request"
        403:
          description: "Permission denied"
        404:
          description: "Endpoint not found"
        500:
          description: "An unknown error occured"
      security:
      - jwt: []
      x-swagger-router-controller: "Profiles"
  /profiles/{id}/firstName:
    patch:
      tags:
      - "Profiles"
      description: "Update right holder's first name with the given ID"
      operationId: "patchProfileFirstName"
      parameters:
      - name: "id"
        in: "path"
        description: "The rights holder's unique profile ID"
        required: true
        type: "integer"
      - in: "body"
        name: "firstName"
        description: "The rights holder's first name"
        required: true
        schema:
          $ref: "#/definitions/profile/properties/firstName"
      responses:
        200:
          description: "OK"
          schema:
            properties:
              name:
                type: "string"
                example: "John"
                description: "The right holder's first name"
        400:
          description: "Bad request"
        403:
          description: "Permission denied"
        404:
          description: "Endpoint not found"
        500:
          description: "An unknown error occured"
      x-swagger-router-controller: "Profiles"
  /profiles/{id}/lastName:
    patch:
      tags:
      - "Profiles"
      description: "Update right holder's last name with the given ID"
      operationId: "patchProfileLastName"
      parameters:
      - name: "id"
        in: "path"
        description: "The rights holder's unique profile ID"
        required: true
        type: "integer"
      - in: "body"
        name: "lastName"
        description: "The rights holder's last name"
        required: true
        schema:
          $ref: "#/definitions/profile/properties/lastName"
      responses:
        200:
          description: "OK"
          schema:
            properties:
              name:
                type: "string"
                example: "Smith"
                description: "The right holder's last name"
        400:
          description: "Bad request"
        403:
          description: "Permission denied"
        404:
          description: "Endpoint not found"
        500:
          description: "An unknown error occured"
      x-swagger-router-controller: "Profiles"
  /profiles/{id}/email:
    patch:
      tags:
      - "Profiles"
      description: "Update right holder's email address with given ID"
      operationId: "patchProfileEmail"
      parameters:
      - name: "id"
        in: "path"
        description: "The right holder's unique profile ID"
        required: true
        type: "integer"
      - in: "body"
        name: "email"
        description: "The rights holder's email address"
        required: true
        schema:
          $ref: "#/definitions/profile/properties/email"
      responses:
        200:
          description: "OK"
          schema:
            properties:
              email:
                type: "string"
                example: "bob.andrews@example.com"
                description: "The right holder's email address"
        400:
          description: "Bad request"
        403:
          description: "Permission denied"
        404:
          description: "Endpoint not found"
        500:
          description: "An unknown error occured"
      security:
      - jwt: []
      x-swagger-router-controller: "Profiles"
  /profiles/{id}/contributorRole:
    patch:
      tags:
      - "Profiles"
      description: "Update right holder's role with the given ID       (Or list of\
        \ roles including copyright, performance, and/or recording)"
      operationId: "patchProfileContributorRole"
      parameters:
      - name: "id"
        in: "path"
        description: "The right holder's unique profile ID"
        required: true
        type: "integer"
      - in: "body"
        name: "contributorRole"
        description: "The right holder's role"
        required: true
        schema:
          $ref: "#/definitions/profile/properties/contributorRole"
      responses:
        200:
          description: "OK"
          schema:
            properties:
              contributorRole:
                type: "string"
                example: "writer"
                description: "The right holder's role"
        400:
          description: "Bad request"
        403:
          description: "Permission denied"
        404:
          description: "Endpoint not found"
        500:
          description: "An unknown error occured"
      x-swagger-router-controller: "Profiles"
  /profiles/{id}/ipi:
    patch:
      tags:
      - "Profiles"
      description: "Update right holder's IPI number"
      operationId: "patchProfileIPI"
      parameters:
      - name: "id"
        in: "path"
        description: "The right holder's unique profile ID"
        required: true
        type: "integer"
      - in: "body"
        name: "ipi"
        description: "The right holder's IPI number"
        required: true
        schema:
          $ref: "#/definitions/profile/properties/ipi"
      responses:
        200:
          description: "OK"
          schema:
            properties:
              ipi:
                type: "string"
                example: "00004576"
                description: "The right holder's interested party information number"
        400:
          description: "Bad request"
        403:
          description: "Permission denied"
        404:
          description: "Endpoint not found"
        500:
          description: "An unknown error occured"
      x-swagger-router-controller: "Profiles"
  /profiles/{id}/media:
    patch:
      tags:
      - "Profiles"
      description: "Update list of media for the given right holder"
      operationId: "patchProfileMedia"
      parameters:
      - name: "id"
        in: "path"
        description: "The right holder's unique profile ID"
        required: true
        type: "integer"
      - in: "body"
        name: "mediaId"
        description: "The unique ID of the given media"
        required: true
        schema:
          $ref: "#/definitions/mediaIds"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/profile"
        400:
          description: "Bad request"
        403:
          description: "Permission denied"
        404:
          description: "Endpoint not found"
        500:
          description: "An unknown error occured"
      x-swagger-router-controller: "Profiles"
  /profiles/{id}/wallet:
    patch:
      tags:
      - "Profiles"
      description: "Update the wallet address of a right holder"
      operationId: "patchProfileWallet"
      parameters:
      - name: "id"
        in: "path"
        description: "The right holder's unique profile ID"
        required: true
        type: "integer"
      - in: "body"
        name: "wallet"
        description: "The right holder's wallet address"
        required: true
        schema:
          $ref: "#/definitions/profile/properties/wallet"
      responses:
        200:
          description: "OK"
          schema:
            properties:
              wallet:
                type: "string"
                example: "0xdd87ae15f4be97e2739c9069ddef674f907d27a9"
                description: "The user's wallet address"
        400:
          description: "Bad request"
        403:
          description: "Permission denied"
        404:
          description: "Endpoint not found"
        500:
          description: "An unknown error occured"
      x-swagger-router-controller: "Profiles"
  /media:
    get:
      tags:
      - "Media"
      description: "Get a list of all media"
      operationId: "getAllMedia"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/medias"
        400:
          description: "Bad request"
        403:
          description: "Permission denied"
        404:
          description: "Endpoint not found"
        500:
          description: "An unknown error occured"
      x-swagger-router-controller: "Media"
    post:
      tags:
      - "Media"
      description: "This method creates a new media item"
      operationId: "postMedia"
      parameters:
      - in: "body"
        name: "body"
        description: "request"
        required: true
        schema:
          $ref: "#/definitions/media"
      responses:
        200:
          description: "OK. The media was created."
          schema:
            $ref: "#/definitions/media"
        400:
          description: "Bad request"
        403:
          description: "Permission denied"
        404:
          description: "Endpoint not found"
        500:
          description: "An unknown error occured"
      security:
      - jwt: []
      x-swagger-router-controller: "Media"
  /media/{mediaId}:
    get:
      tags:
      - "Media"
      description: "Get media with the given ID"
      operationId: "getMedia"
      parameters:
      - name: "mediaId"
        in: "path"
        description: "The artwork agreement's unique ID"
        required: true
        type: "integer"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/media"
        400:
          description: "Bad request"
        403:
          description: "Permission denied"
        404:
          description: "Endpoint not found"
        500:
          description: "An unknown error occured"
      x-swagger-router-controller: "Media"
    put:
      tags:
      - "Media"
      description: "Update media with the given ID"
      operationId: "updateMedia"
      parameters:
      - name: "mediaId"
        in: "path"
        description: "The artwork agreement's unique ID"
        required: true
        type: "integer"
      - in: "body"
        name: "body"
        description: "request"
        required: true
        schema:
          $ref: "#/definitions/media"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/media"
        400:
          description: "Bad request"
        403:
          description: "Permission denied"
        404:
          description: "Endpoint not found"
        500:
          description: "An unknown error occured"
      x-swagger-router-controller: "Media"
    delete:
      tags:
      - "Media"
      description: "Delete a right holder's profile with the given ID"
      operationId: "deleteMedia"
      parameters:
      - name: "mediaId"
        in: "path"
        description: "The rights holder's unique profile ID"
        required: true
        type: "integer"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad request"
        403:
          description: "Permission denied"
        404:
          description: "Endpoint not found"
        500:
          description: "An unknown error occured"
      security:
      - jwt: []
      x-swagger-router-controller: "Media"
  /media/{mediaId}/title:
    patch:
      tags:
      - "Media"
      description: "Update the title of the given media identified by ID"
      operationId: "patchMediaTitle"
      parameters:
      - name: "mediaId"
        in: "path"
        description: "The artwork agreement's unique ID"
        required: true
        type: "integer"
      - in: "body"
        name: "title"
        description: "The title of the artwork"
        required: true
        schema:
          $ref: "#/definitions/media/properties/title"
      responses:
        200:
          description: "OK"
          schema:
            properties:
              title:
                type: "string"
                example: "Love You Honey"
                description: "The title of the given artwork"
        400:
          description: "Bad request"
        403:
          description: "Permission denied"
        404:
          description: "Endpoint not found"
        500:
          description: "An unknown error occured"
      x-swagger-router-controller: "Media"
  /media/{mediaId}/description:
    patch:
      tags:
      - "Media"
      description: "Update the description of a piece of media"
      operationId: "patchMediaDescription"
      parameters:
      - name: "mediaId"
        in: "path"
        description: "The artwork agreement's unique ID"
        required: true
        type: "integer"
      - in: "body"
        name: "description"
        description: "The description of the artwork"
        required: true
        schema:
          $ref: "#/definitions/media/properties/description"
      responses:
        200:
          description: "OK"
          schema:
            properties:
              description:
                type: "string"
                example: "The wonderful classic hit song, Love You Honey"
                description: "The description of the artwork"
        400:
          description: "Bad request"
        403:
          description: "Permission denied"
        404:
          description: "Endpoint not found"
        500:
          description: "An unknown error occured"
      x-swagger-router-controller: "Media"
  # /media/{mediaId}/rightHolders:
  #   get:
  #     tags:
  #     - "Media"
  #     description: "Get the right holders who collaborated on media"
  #     operationId: "getMediaRightHolders"
  #     parameters:
  #     - name: "mediaId"
  #       in: "path"
  #       description: "The artwork agreement's unique ID"
  #       required: true
  #       type: "integer"
  #     responses:
  #       200:
  #         description: "OK"
  #         schema:
  #           properties:
  #             rightHolders:
  #               type: "object"
  #               description: "The full name of the right holder"
  #               additionalProperties:
  #                 type: "string"
  #                 description: "The type of right holder, for example, writer, producer"
  #       400:
  #         description: "Bad request"
  #       403:
  #         description: "Permission denied"
  #       404:
  #         description: "Endpoint not found"
  #       500:
  #         description: "An unknown error occured"
  #     x-swagger-router-controller: "Media"
  /media/{mediaId}/jurisdiction:
    patch:
      tags:
      - "Media"
      description: "Update the jurisdiction of the given media"
      operationId: "patchMediaJurisdiction"
      parameters:
      - name: "mediaId"
        in: "path"
        description: "The artwork agreement's unique ID"
        required: true
        type: "integer"
      - in: "body"
        name: "jurisdiction"
        description: "The jurisdiction of the given media"
        required: true
        schema:
          $ref: "#/definitions/media/properties/jurisdiction"
      responses:
        200:
          description: "OK"
          schema:
            properties:
              jurisdiction:
                type: "string"
                example: "SOPROQ"
                description: "The jusrisdiction of the artwork agreement of the given\
                  \ media"
        400:
          description: "Bad request"
        403:
          description: "Permission denied"
        404:
          description: "Endpoint not found"
        500:
          description: "An unknown error occured"
      x-swagger-router-controller: "Media"
  /media/{mediaId}/modificationDate:
    patch:
      tags:
      - "Media"
      description: "Update the modification date of the given media"
      operationId: "patchModificationDate"
      parameters:
      - name: "mediaId"
        in: "path"
        description: "The artwork agreement's unique ID"
        required: true
        type: "integer"
      - in: "body"
        name: "modificationDate"
        description: "The date the rights agreement for the given media was modified"
        required: true
        schema:
          $ref: "#/definitions/media/properties/modificationDate"
      responses:
        200:
          description: "OK"
          schema:
            properties:
              modificationDate:
                type: "string"
                format: "iso8601-date-time"
                example: "2019-01-01T15:53:00"
        400:
          description: "Bad request"
        403:
          description: "Permission denied"
        404:
          description: "Endpoint not found"
        500:
          description: "An unknown error occured"
      x-swagger-router-controller: "Media"
  /media/{mediaId}/publishDate:
    patch:
      tags:
      - "Media"
      description: "Update the publish date of the given media"
      operationId: "patchPublishDate"
      parameters:
      - name: "mediaId"
        in: "path"
        description: "The artwork agreement's unique ID"
        required: true
        type: "integer"
      - in: "body"
        name: "publishDate"
        description: "The date the given media was published"
        required: true
        schema:
          $ref: "#/definitions/media/properties/publishDate"
      responses:
        200:
          description: "OK"
          schema:
            properties:
              publishDate:
                type: "string"
                format: "iso8601-date-time"
                example: "2019-01-01T15:53:00"
        400:
          description: "Bad request"
        403:
          description: "Permission denied"
        404:
          description: "Endpoint not found"
        500:
          description: "An unknown error occured"
      x-swagger-router-controller: "Media"
  # /media/{mediaId}/rightsType:
  #   get:
  #     tags:
  #     - "Media"
  #     description: "Get the type of rights of the given media         (Including copyright,\
  #       \ performance, recording)"
  #     operationId: "getMediaRightsType"
  #     parameters:
  #     - name: "mediaId"
  #       in: "path"
  #       description: "The artwork agreement's unique ID"
  #       required: true
  #       type: "integer"
  #     responses:
  #       200:
  #         description: "OK"
  #         schema:
  #           properties:
  #             rightsType:
  #               type: "object"
  #               example:
  #                 copyright: true
  #                 performance: true
  #                 recording: false
  #               description: "The type of rights associated with the artwork"
  #               properties: {}
  #       400:
  #         description: "Bad request"
  #       403:
  #         description: "Permission denied"
  #       404:
  #         description: "Endpoint not found"
  #       500:
  #         description: "An unknown error occured"
  #     x-swagger-router-controller: "Media"
  /media/{mediaId}/genre:
    patch:
      tags:
      - "Media"
      description: "Update the genre of the media with the given ID"
      operationId: "patchMediaGenre"
      parameters:
      - name: "mediaId"
        in: "path"
        description: "The artwork agreement's unique ID"
        required: true
        type: "integer"
      - in: "body"
        name: "genre"
        description: "The genre of the artwork"
        required: true
        schema:
          $ref: "#/definitions/media/properties/genre"
      responses:
        200:
          description: "OK"
          schema:
            properties:
              genre:
                type: "string"
                example: "Pop"
                description: "The genre of the given media."
        400:
          description: "Bad request"
        403:
          description: "Permission denied"
        404:
          description: "Endpoint not found"
        500:
          description: "An unknown error occured"
      x-swagger-router-controller: "Media"
  /media/{mediaId}/secondaryGenre:
    patch:
      tags:
      - "Media"
      description: "Update the secondary genre of the media with the given ID"
      operationId: "patchMediaSecondaryGenre"
      parameters:
      - name: "mediaId"
        in: "path"
        description: "The artwork agreement's unique ID"
        required: true
        type: "integer"
      - in: "body"
        name: "secondaryGenre"
        description: "The secondary genre of the artwork"
        required: true
        schema:
          $ref: "#/definitions/media/properties/secondaryGenre"
      responses:
        200:
          description: "OK"
          schema:
            properties:
              secondaryGenre:
                type: "string"
                example: "Pop"
                description: "The secondary genre of the given media."
        400:
          description: "Bad request"
        403:
          description: "Permission denied"
        404:
          description: "Endpoint not found"
        500:
          description: "An unknown error occured"
      x-swagger-router-controller: "Media"
  /media/{mediaId}/album:
    patch:
      tags:
      - "Media"
      description: "Update the album name of the media with the given ID"
      operationId: "patchMediaAlbum"
      parameters:
      - name: "mediaId"
        in: "path"
        description: "The artwork agreement's unique ID"
        required: true
        type: "integer"
      - in: "body"
        name: "album"
        description: "The album of the artwork"
        required: true
        schema:
          $ref: "#/definitions/media/properties/album"
      responses:
        200:
          description: "OK"
          schema:
            properties:
              genre:
                type: "string"
                example: "Love you Baby"
                description: "The genre of the given media."
        400:
          description: "Bad request"
        403:
          description: "Permission denied"
        404:
          description: "Endpoint not found"
        500:
          description: "An unknown error occured"
      x-swagger-router-controller: "Media"
  # /media/{mediaId}/creationDate:
  #   get:
  #     tags:
  #     - "Media"
  #     description: "Get creation date of the media with the given ID"
  #     operationId: "getMediaCreationDate"
  #     parameters:
  #     - name: "mediaId"
  #       in: "path"
  #       description: "The artwork agreement's unique ID"
  #       required: true
  #       type: "integer"
  #     responses:
  #       200:
  #         description: "OK"
  #         schema:
  #           properties:
  #             creationDate:
  #               type: "string"
  #               format: "iso8601-date-time"
  #               example: "2019-01-01T15:53:00"
  #               description: "The creation date of the smartsplit contract for the\
  #                 \ given media"
  #       400:
  #         description: "Bad request"
  #       403:
  #         description: "Permission denied"
  #       404:
  #         description: "Endpoint not found"
  #       500:
  #         description: "An unknown error occured"
  #     x-swagger-router-controller: "Media"
  /media/{mediaId}/publisher:
    patch:
      tags:
      - "Media"
      description: "Update publisher of the media with the given ID"
      operationId: "patchMediaPublisher"
      parameters:
      - name: "mediaId"
        in: "path"
        description: "The artwork agreement's unique ID"
        required: true
        type: "integer"
      - in: "body"
        name: "publisher"
        description: "The publisher of the media"
        required: true
        schema:
          $ref: "#/definitions/media/properties/publisher"
      responses:
        200:
          description: "OK"
          schema:
            properties:
              publisher:
                type: "string"
                example: "tune publishing"
                description: "The publisher name of the media with the given ID"
        400:
          description: "Bad request"
        403:
          description: "Permission denied"
        404:
          description: "Endpoint not found"
        500:
          description: "An unknown error occured"
      x-swagger-router-controller: "Media"
  # /media/{mediaId}/rightsSplit:
  #   get:
  #     tags:
  #     - "Media"
  #     description: "Get rights holders' percentage split given media"
  #     operationId: "getMediaRightsSplit"
  #     parameters:
  #     - name: "mediaId"
  #       in: "path"
  #       description: "The artwork agreement's unique ID"
  #       required: true
  #       type: "integer"
  #     responses:
  #       200:
  #         description: "OK"
  #         schema:
  #           properties:
  #             rightsSplit:
  #               type: "object"
  #               description: "The percentage split of each right holder"
  #               additionalProperties:
  #                 type: "number"
  #                 description: "The names of the right holders for the given media"
  #       400:
  #         description: "Bad request"
  #       403:
  #         description: "Permission denied"
  #       404:
  #         description: "Endpoint not found"
  #       500:
  #         description: "An unknown error occured"
  #     security:
  #     - jwt: []
  #     x-swagger-router-controller: "Media"
  /payments:
    get:
      tags:
      - "Payments"
      description: "Get a list of all payments' details"
      operationId: "getAllPayments"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/payments"
        400:
          description: "Bad request"
        403:
          description: "Permission denied"
        404:
          description: "Endpoint not found"
        500:
          description: "An unknown error occured"
      x-swagger-router-controller: "Payments"
    post:
      tags:
      - "Payments"
      description: "Add a new payment"
      operationId: "postPayment"
      parameters:
      - in: "body"
        name: "body"
        description: "The payment details"
        required: true
        schema:
          $ref: "#/definitions/payment"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/payment"
        400:
          description: "Bad request"
        403:
          description: "Permission denied"
        404:
          description: "Endpoint not found"
        500:
          description: "An unknown error occured"
      x-swagger-router-controller: "Payments"
  /payments/{id}:
    get:
      tags:
      - "Payments"
      description: "Get the details of a payment with the given ID"
      operationId: "getPayment"
      parameters:
      - name: "id"
        in: "path"
        description: "The payment's unique ID"
        required: true
        type: "number"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/payment"
        400:
          description: "Bad request"
        403:
          description: "Permission denied"
        404:
          description: "Endpoint not found"
        500:
          description: "An unknown error occured"
      x-swagger-router-controller: "Payments"
    put:
      tags:
      - "Payments"
      description: "Update the details of a payment with the given ID"
      operationId: "updatePayment"
      parameters:
      - name: "id"
        in: "path"
        description: "The payment's unique ID"
        required: true
        type: "integer"
      - in: "body"
        name: "body"
        description: "The payment details"
        required: true
        schema:
          $ref: "#/definitions/payment"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/payment"
        400:
          description: "Bad request"
        403:
          description: "Permission denied"
        404:
          description: "Endpoint not found"
        500:
          description: "An unknown error occured"
      x-swagger-router-controller: "Payments"
    delete:
      tags:
      - "Payments"
      description: "Delete a right holder's profile with the given ID"
      operationId: "deletePayment"
      parameters:
      - name: "id"
        in: "path"
        description: "The rights holder's unique profile ID"
        required: true
        type: "integer"
      responses:
        200:
          description: "OK. Payment deleted"
        400:
          description: "Bad request"
        403:
          description: "Permission denied"
        404:
          description: "Endpoint not found"
        500:
          description: "An unknown error occured"
      security:
      - jwt: []
      x-swagger-router-controller: "Payments"
  /payments/{id}/transactionId:
    patch:
      tags:
      - "Payments"
      description: "Update management societies' payment transaction ID"
      operationId: "patchPaymentTransactionID"
      parameters:
      - name: "id"
        in: "path"
        description: "The payment's unique ID"
        required: true
        type: "number"
      - in: "body"
        name: "transactionId"
        description: "The payment transaction ID"
        required: true
        schema:
          $ref: "#/definitions/payment/properties/transactionId"
      responses:
        200:
          description: "OK"
          schema:
            properties:
              transactionId:
                type: "string"
                example: "87654321"
                description: "The management societies' transaction ID"
        400:
          description: "Bad request"
        403:
          description: "Permission denied"
        404:
          description: "Endpoint not found"
        500:
          description: "An unknown error occured"
      security:
      - jwt: []
      x-swagger-router-controller: "Payments"
  /payments/{id}/transactionHash:
    patch:
      tags:
      - "Payments"
      description: "Update blockchain transaction hash of a payment"
      operationId: "patchPaymentTransactionHash"
      parameters:
      - name: "id"
        in: "path"
        description: "The payment's unique ID"
        required: true
        type: "number"
      - in: "body"
        name: "transactionHash"
        description: "The blockchain hash of the transaction"
        required: true
        schema:
          $ref: "#/definitions/payment/properties/transactionHash"
      responses:
        200:
          description: "OK"
          schema:
            properties:
              transactionHash:
                type: "string"
                example: "0x68a4c5ff945f8f1c0d0218466886d1e860c78cb625a2a4860e1efaf3a7c33b0c"
                description: "The transaction hash on the blockchain"
        400:
          description: "Bad request"
        403:
          description: "Permission denied"
        404:
          description: "Endpoint not found"
        500:
          description: "An unknown error occured"
      security:
      - jwt: []
      x-swagger-router-controller: "Payments"
securityDefinitions:
  basicAuth:
    description: "HTTP Basic Authentication"
    type: "basic"
  jwt:
    description: "A JSON Web Token (JWT) used for access control and authorization"
    type: "apiKey"
    name: "Authorization"
    in: "header"
definitions:
  auth:
    properties:
      apiKey:
        type: "string"
      username:
        type: "string"
      password:
        type: "string"
  authResult:
    type: "object"
    properties:
      accessToken:
        type: "string"
        example: "fyJhbGciOiJIUzI1NiIsInR5cCI6IkpXUyJ9.eyJjb21wYW55IjoiRnV0dXJlRWQiLCJzdWIiOjEsImlzcyI6Imh0dHA6XC9cL2Z1dHVyZWVkLmRldlwvYXBpXC92MVwvc3R1ZGVudFwvbG9naW5cL3VzZXJuYW1lIiwiaWF0IjoiMTQyNzQyNjc3MSIsImV4cCI6IjE0Mjc0MzAzNzEiLCJuYmYiOiIxNDI3NDI2NzcxIiwianRpIjoiNmFlZDQ3MGFiOGMxYTk0MmE0MTViYTAwOTBlMTFlZTUifQ.MmM2YTUwMjEzYTE0OGNhNjk5Y2Y2MjEwZDdkN2Y1OTQ2NWVhZTdmYmI4OTA5YmM1Y2QwYTMzZjUwNTgwY2Y0MQ"
        description: "The JWT access token for the current session"
    example:
      accessToken: "fyJhbGciOiJIUzI1NiIsInR5cCI6IkpXUyJ9.eyJjb21wYW55IjoiRnV0dXJlRWQiLCJzdWIiOjEsImlzcyI6Imh0dHA6XC9cL2Z1dHVyZWVkLmRldlwvYXBpXC92MVwvc3R1ZGVudFwvbG9naW5cL3VzZXJuYW1lIiwiaWF0IjoiMTQyNzQyNjc3MSIsImV4cCI6IjE0Mjc0MzAzNzEiLCJuYmYiOiIxNDI3NDI2NzcxIiwianRpIjoiNmFlZDQ3MGFiOGMxYTk0MmE0MTViYTAwOTBlMTFlZTUifQ.MmM2YTUwMjEzYTE0OGNhNjk5Y2Y2MjEwZDdkN2Y1OTQ2NWVhZTdmYmI4OTA5YmM1Y2QwYTMzZjUwNTgwY2Y0MQ"
  profiles:
    type: "array"
    description: "An array of profile information"
    items:
      $ref: "#/definitions/profile"
  profile:
    type: "object"
    properties:
      id:
        type: integer
        example: 1
        description: "The unique ID of the given profile"
      firstName:
        type: "string"
        example: "John"
        description: "The name displayed on the user's profile"
      lastName:
        type: "string"
        example: "Smith"
        description: "The name displayed on the user's profile"
      email:
        type: "string"
        example: "john.smith@example.com"
        description: "The email address for this user profile"
      media:
        $ref: "#/definitions/mediaIds"
      ipi:
        type: "string"
        example: "00004576"
        description: "The right holder's interested party information number"
      contributorRole:
        type: "string"
        example: "writer"
        description: "The role of the right holder for this user profile"
      wallet:
        type: "string"
        example: "0xdd87ae15f4be97e2739c9069ddef674f907d27a8"
        description: "The blockchain wallet address for this user profile"
    example:
      ipi: "00004576"
      contributorRole: "writer"
      wallet: "0xdd87ae15f4be97e2739c9069ddef674f907d27a8"
      media: ""
      firstName: "John"
      email: "john.smith@example.com"
      lastName: "Smith"
  medias:
    type: "array"
    description: "An array of pieces of media"
    items:
      $ref: "#/definitions/media"
  mediaIds:
    type: "array"
    description: "An array of mediaIds referencing media"
    items:
      type: "integer"
      example: 1
  media:
    properties:
      mediaId:
        type: "integer"
        example: 1
        description: "The id of this piece of media"
      title:
        type: "string"
        example: "Love You Baby"
        description: "The title of this piece of media"
      album:
        type: "string"
        example: "Love You Baby Album"
        description: "The title of the album for this piece of media"
      description:
        type: "string"
        example: "The wonderful classic hit song, Love You Baby"
        description: "The short descriptioon of this piece of media"
      cover:
        type: "boolean"
        example: false
        description: "Whether or not this piece of media is a cover"
      rightHolders:
        type: "object"
        description: "The full name of the right holder"
        additionalProperties:
          type: "string"
          description: "The type of right holder, for example, writer, producer"
      jurisdiction:
        type: "string"
        example: "SOCAN"
        description: "The Jurisdiction for the given media"
      rightsType:
        type: "object"
        description: "The boolean, 'True' or 'False'"
        additionalProperties:
          type: "string"
          description: "The type of right, for example, copyright, performance, recording"
      genre:
        type: "string"
        example: "Rock"
        description: "The genre of the given media"
      secondaryGenre:
        type: "string"
        example: "Hip Hop"
        description: "The secondary genre of the given media"
      creationDate:
        type: "string"
        format: "iso8601-date-time"
        example: "2019-01-01T15:53:00"
        description: "The creation date of the rights agreement for the given media"
      modificationDate:
        type: "string"
        format: "iso8601-date-time"
        example: "2019-01-01T15:53:00"
        description: "The date the rights agreement for the given media was modified"
      publishDate:
        type: "string"
        format: "iso8601-date-time"
        example: "2019-01-01T15:53:00"
        description: "The date of first broadcast/publication for the given media"
      publisher:
        type: "string"
        example: "sync publishing"
        description: "The publisher for the given media (Left blank if no publisher)"
      rightsSplit:
        type: "object"
        description: "The percentage split of each right holder"
        additionalProperties:
          type: "number"
          description: "The names of the right holders for the given media"
    example:
      rightsSplit:
        key: 0.80082819046101150206595775671303272247314453125
      jurisdiction: "SOCAN"
      genre: "Rock"
      description: "The wonderful classic hit song, Love You Baby"
      creationDate: "2019-01-01T15:53:00"
      cover: false
      publisher: "sync publishing"
      rightsType:
        key: "rightsType"
      title: "Love You Baby"
      rightHolders:
        key: "rightHolders"
  payments:
    type: "array"
    description: "An array of information about payments"
    items:
      $ref: "#/definitions/payment"
  payment:
    type: "object"
    properties:
      id:
        type: "integer"
        example: 1
        description: "Media ID related to this payment"
      amount: 
        type: "number"
        example: 20
        description: "The amount of the payment in $ CAD"
      payee: 
        type: "number"
        example: 2
        description: "The ID of the profile of the creator who was paid"
      transactionId:
        type: "string"
        example: "12345678"
        description: "The transaction string of the management company for this payment"
      transactionHash:
        type: "string"
        example: "0x58a4c5ff945f8f1c0d0218466886d1e860c78cb625a2a4860e1efaf3a7c33b0c"
        description: "The blockchain transaction hash for this payment"
    example:
      transactionId: "12345678"
      id: 1
      amount: 20
      transactionHash: "0x58a4c5ff945f8f1c0d0218466886d1e860c78cb625a2a4860e1efaf3a7c33b0c"
